version: '3'
services:
  web:
    container_name: hive-game
    build: ./src/
    ports:
      - "8000:80"
    depends_on:
      - db
      - ai

  db:
    container_name: hive-db
    build: ./database/
    environment:
      MYSQL_ROOT_PASSWORD: EstaCR7
      MYSQL_DATABASE: hive
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d


  ai:
    build: ./ai/
    container_name: hive-ai
    ports:
      - "5000:5000"